<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>box_Chat message conversation</name>
   <tag></tag>
   <elementGuidId>e8499bea-d9ee-4cbf-9768-50c19585248a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;conversations&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>d95dedcf-3aaa-47b3-bfd1-abc222fa17e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>57723a38-37b9-4786-83b9-12dbe76d6679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat&quot;)/qontak-webchat[1]/div[1]/div[1]/div[1]/div[@class=&quot;qchat-messenger&quot;]/div[@class=&quot;q-d-flex&quot;]/div[@class=&quot;qchat-messenger__heading q-d-flex q-justify-content-between&quot;]/div[@class=&quot;q-d-flex&quot;]/p[@class=&quot;q-m-0&quot;]/span[@class=&quot;q-pointer q-ml-1&quot;]/u[1]</value>
      <webElementGuid>9baaa9d9-45e0-4ae6-ba0e-ff640ecf1e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Web Perqara/OBJR Home Unlogin Menu/OBJR Chat Message/iframe_Chat message</value>
      <webElementGuid>38888da3-55e2-4e9e-b641-6d33282abc6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div/div/div/div/div/p/span/u</value>
      <webElementGuid>556caeed-27b3-4f2c-98ca-94a491372995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome, nikojona@gmail.com!'])[1]/preceding::u[1]</value>
      <webElementGuid>2fc5d84d-1514-464d-9383-cb0f54fb2d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::u[1]</value>
      <webElementGuid>8fac43b0-f081-47ce-95f6-72e15c50feb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>21416861-48a7-4c5f-b989-2173364d6610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>8d24e024-ed87-4a07-949e-86ad971696b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>8840097f-4e9d-42cd-805b-c40d6da5a17a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
