<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Chat message box emoji</name>
   <tag></tag>
   <elementGuidId>71960b44-e30b-43f4-84eb-b4eb7986c215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmojiPicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='grid-emojis']/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>134702d3-feca-475e-b8f9-7c58c561233e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmojiPicker</value>
      <webElementGuid>a8861ca7-46bf-44bf-b987-3832f2c7ac2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>emoji-picker</value>
      <webElementGuid>8409dd9d-3307-487c-ae19-6e4b712d16e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label-search</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>6b0ce6c8-39f9-418e-b6cb-06e875eb7681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>pt-BR</value>
      <webElementGuid>0cba57b5-91fa-4bce-983d-ba3a055ea3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmojiPicker&quot;)</value>
      <webElementGuid>e7c67ff4-fb25-4cd6-9073-57c44c3584f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Web Perqara/OBJR Home Unlogin Menu/OBJR Chat Message/iframe_Chat message</value>
      <webElementGuid>d404bb51-1ebb-40c7-9e2f-591302c63880</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='EmojiPicker']</value>
      <webElementGuid>b4dec2d5-97d6-4cea-9366-333b6075042e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div/div/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>43bf81b3-db26-42b0-a223-9c6d1971961a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halo 2'])[1]/following::div[2]</value>
      <webElementGuid>8acd8d3b-2fb0-4fce-8c3a-60bfc547a3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halo'])[1]/following::div[8]</value>
      <webElementGuid>5ed5ba12-7f94-40c7-b84a-ee67bbadec20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'EmojiPicker', '&quot;', ')')])[1]/preceding::div[21]</value>
      <webElementGuid>d5cce026-7997-4e9d-99c1-3beeb2f26b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>2d57399c-ae79-4a1d-9d1a-ba98ef2cb151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'EmojiPicker']</value>
      <webElementGuid>840f9932-1584-42ed-bb74-bf34fb0e4fde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
