<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Chat message</name>
   <tag></tag>
   <elementGuidId>881b5bc8-6919-401f-b24a-d28bfdffba3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qontak-webchat-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='qontak-webchat-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>daad3515-070e-4312-b8cb-fbf19406d69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://webchat.qontak.com?c=fPkthggPmqmq1U8OeMBGLA&amp;i=b3ba6f13-b622-47e0-88a4-fe173d7b80c2&amp;d=https://perqara.com&amp;w=1200&amp;h=707</value>
      <webElementGuid>b5fef651-2871-4801-86c1-ca0f6a460eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qontak-webchat-widget</value>
      <webElementGuid>be2dc24a-8350-4c01-8024-5969e98bf5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>89d01bd8-949a-4c98-b20a-3e0d342d1081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5b5dd6e0-5551-4209-b0ef-917d65d25ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webkitallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc2faa24-bf9e-4dd5-b51a-d4edb0a4e786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mozallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6521b6ac-bde7-435c-a857-ebb8046d6f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>380px</value>
      <webElementGuid>44861cee-7b12-4003-a465-866bbe34f185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>590px</value>
      <webElementGuid>a36e08e2-c805-4570-a542-3baa1bcfcd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat-widget&quot;)</value>
      <webElementGuid>3910b70c-a974-47bb-a8dd-522dff9523f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='qontak-webchat-widget']</value>
      <webElementGuid>1684f0dc-ce3d-4001-898e-7f0b12b011ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1128cc86-c035-4cc0-9ad2-d39b9bed1d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://webchat.qontak.com?c=fPkthggPmqmq1U8OeMBGLA&amp;i=b3ba6f13-b622-47e0-88a4-fe173d7b80c2&amp;d=https://perqara.com&amp;w=1200&amp;h=707' and @id = 'qontak-webchat-widget']</value>
      <webElementGuid>fe3133ee-8dae-4d19-ac6b-db7b8af508fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
