<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Chat message today</name>
   <tag></tag>
   <elementGuidId>1be8e302-e595-4fde-8c9a-6a90ac6cba1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.qchat-conv__divider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;qchat-conv__divider&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d70df088-8f6c-4ef9-8d10-141bf850c245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qchat-conv__divider</value>
      <webElementGuid>69c0c8d8-778e-4517-92be-9d1bef183b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Today </value>
      <webElementGuid>0f5701a1-9508-46eb-a787-880db2516602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;conversations&quot;)/div[@class=&quot;qslidein5s&quot;]/div[@class=&quot;qchat-conv__divider&quot;]</value>
      <webElementGuid>dc091aa7-d432-4e33-a66d-943356b55c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Web Perqara/OBJR Home Unlogin Menu/OBJR Chat Message/iframe_Chat message</value>
      <webElementGuid>a916f143-d2d2-42f5-95b7-63e4a3ac3496</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='conversations']/div/div</value>
      <webElementGuid>698ff1d0-7519-4f93-bff0-d7906933d774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome, nikojona@gmail.com!'])[1]/following::div[6]</value>
      <webElementGuid>4fb8e625-ef2b-495e-a601-9bd802acde4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[10]</value>
      <webElementGuid>3f2ac975-8401-4272-9b65-38dcd16a5c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gmail.com'])[1]/preceding::div[1]</value>
      <webElementGuid>381b9eb7-9741-4124-95b0-9192bb701c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>c05bf8e0-b4d7-4654-a6f2-c57cbcf2b7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>8122d010-ffa6-4d9b-a946-ad0c2debabf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Today ' or . = ' Today ')]</value>
      <webElementGuid>9dc6778a-4476-42de-b0bc-2eb178142988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
