<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_kategori Pidana</name>
   <tag></tag>
   <elementGuidId>3e108a9e-ae24-4bf9-8ae8-7de41cf55164</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.m-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='index-section']/div/section/div[2]/div[1]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1462dc06-3744-4c17-91a7-8e5d9d36a17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/public-perqara/icon/20220316_Marketing_Icon_Pidana.png</value>
      <webElementGuid>ad2ad749-f883-4510-aeaa-b91402e2ea65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>bd6a7553-7247-4868-81e3-9ddd532bd84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index-section&quot;)/div[1]/section[@class=&quot;categories-filter mx-6 md:mx-0 my-16&quot;]/div[@class=&quot;grid grid-cols-2 md:grid-cols-5 xl:grid-cols-6 gap-5 my-10&quot;]/div[@class=&quot;categories-container
              shadow-lg
              h-48
              md:h-56
              w-full
              rounded-lg
              relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/div[@class=&quot;w-16
                    h-16
                    rounded-full
                    justify-center
                    items-center
                    flex
                    bg-white
                    m-auto&quot;]/img[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>9db7dda1-8f9a-4e5d-8f2a-180c2c4ca3c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='index-section']/div/section/div[2]/div/div/div/div/img</value>
      <webElementGuid>a7795a62-1a9f-4f14-9e03-8454dc16a4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://storage.googleapis.com/public-perqara/icon/20220316_Marketing_Icon_Pidana.png')]</value>
      <webElementGuid>83cb432c-028b-4af4-99bc-08d9c34ea687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/img</value>
      <webElementGuid>1ac00d91-8f29-43df-b83e-c7e726e33220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/public-perqara/icon/20220316_Marketing_Icon_Pidana.png']</value>
      <webElementGuid>1ba18f5f-920e-4f68-9177-178943403fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
