<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_menu top Daftar</name>
   <tag></tag>
   <elementGuidId>82a479da-d8ce-49b1-bf35-7b510798c735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/header/div[2]/nav/ul/li[6]/ul/li[3]/a/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0cee89f3-ef40-4ea4-b37f-0739a2e79a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
                      inline-block
                      text-center
                      self-center
                      py-2
                      px-5
                      text-white
                      md:bg-primary
                      md:border
                      md:border-transparent
                      md:px-8
                      md:py-1
                      md:rounded-md
                    </value>
      <webElementGuid>cd9361c7-a5d4-42cd-8d18-bcc50b3eac54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Daftar
                  </value>
      <webElementGuid>b3ab8415-92ea-4e73-9491-0a0a09002db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[1]/header[@class=&quot;font-avenir absolute w-full z-10&quot;]/div[@class=&quot;flex
        relative
        w-full
        md:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        py-8
        px-6
        md:px-0&quot;]/nav[@class=&quot;ml-5 font-avenir font-medium w-full&quot;]/ul[@class=&quot;flex md:pr-5&quot;]/li[@class=&quot;ml-auto&quot;]/ul[@class=&quot;flex&quot;]/li[@class=&quot;md:text-secondary&quot;]/a[1]/button[@class=&quot;inline-block
                      text-center
                      self-center
                      py-2
                      px-5
                      text-white
                      md:bg-primary
                      md:border
                      md:border-transparent
                      md:px-8
                      md:py-1
                      md:rounded-md&quot;]</value>
      <webElementGuid>3654a35d-6095-42e5-8587-72a53a09077d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/header/div[2]/nav/ul/li[6]/ul/li[3]/a/button</value>
      <webElementGuid>75c6049e-d458-46ce-9333-d53842468396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/following::button[1]</value>
      <webElementGuid>ae17fcda-009f-42a9-ac82-67500bbd737e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[3]/following::button[2]</value>
      <webElementGuid>bfb38878-c605-444a-88da-52f95c493f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[4]/preceding::button[1]</value>
      <webElementGuid>7747ceb4-a612-4c26-912c-4278c15ea5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Advokat'])[4]/preceding::button[1]</value>
      <webElementGuid>65991cb0-8c85-49cf-92c6-16c696b8b1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav/ul/li[6]/ul/li[3]/a/button</value>
      <webElementGuid>5f028ca2-16b4-491e-bcad-6dd4f8942e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                    Daftar
                  ' or . = '
                    Daftar
                  ')]</value>
      <webElementGuid>9a98fc3f-7ee6-412f-8d2b-a35382fb5a29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
