<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_menu top Blog</name>
   <tag></tag>
   <elementGuidId>d4797b46-9d8f-4304-94cc-4596f6930d6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/header/div[2]/nav/ul/li[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1160c874-30ff-4f7f-9568-4b631c0f9e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white</value>
      <webElementGuid>74545c58-bcf8-4447-b764-35184cee63f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Blog
  </value>
      <webElementGuid>9cc01927-345f-489d-82bc-3ab6067ba107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[1]/header[@class=&quot;font-avenir absolute w-full z-10&quot;]/div[@class=&quot;flex
        relative
        w-full
        md:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        py-8
        px-6
        md:px-0&quot;]/nav[@class=&quot;ml-5 font-avenir font-medium w-full&quot;]/ul[@class=&quot;flex md:pr-5&quot;]/li[@class=&quot;hidden md:flex py-2 px-5 content-center relative cursor-pointer&quot;]/button[@class=&quot;text-white&quot;]</value>
      <webElementGuid>22981944-4e9e-445d-ad87-2085338a23a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/header/div[2]/nav/ul/li[3]/button</value>
      <webElementGuid>f5834da8-4f19-46e3-aad3-2e6effd24ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Advokat'])[3]/following::button[1]</value>
      <webElementGuid>49cf4b96-ed49-4564-b15a-d3612e88ace2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[3]/following::button[2]</value>
      <webElementGuid>93023fd5-7a33-4a09-afac-4a801b3b21ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[3]/preceding::button[1]</value>
      <webElementGuid>3db8f473-e8cc-40df-b7cf-d154c9639e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[3]/preceding::button[2]</value>
      <webElementGuid>3b29a121-b71c-4813-9555-4f1019e1a42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav/ul/li[3]/button</value>
      <webElementGuid>20c8c898-cfba-484c-874b-53984587a3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
    Blog
  ' or . = '
    Blog
  ')]</value>
      <webElementGuid>ac1b558b-8acc-4bde-9696-6e9a71bb84cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
