<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_menu top FAQ</name>
   <tag></tag>
   <elementGuidId>6d341a70-480d-4953-93f3-f4cdd87c53d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/header/div[2]/nav/ul/li[4]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9b76e36-556f-4c60-b2fe-7f1715452907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white</value>
      <webElementGuid>dd0e2a29-20fb-49bf-9901-3a0e06638a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      FAQ
    </value>
      <webElementGuid>9c0de4f3-45f7-4f40-909f-950792229a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[1]/header[@class=&quot;font-avenir absolute w-full z-10&quot;]/div[@class=&quot;flex
        relative
        w-full
        md:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        py-8
        px-6
        md:px-0&quot;]/nav[@class=&quot;ml-5 font-avenir font-medium w-full&quot;]/ul[@class=&quot;flex md:pr-5&quot;]/li[@class=&quot;hidden md:flex py-2 px-5 content-center relative cursor-pointer&quot;]/div[@class=&quot;text-white&quot;]/button[@class=&quot;text-white&quot;]</value>
      <webElementGuid>4c1c89e8-d125-4273-ac94-7ef8f24f06d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/header/div[2]/nav/ul/li[4]/div/button</value>
      <webElementGuid>f67e315a-f11f-4c69-80dd-0fd8427c997c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[3]/following::button[1]</value>
      <webElementGuid>8806a772-0772-47e7-b3f1-3b8926d48b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Advokat'])[3]/following::button[2]</value>
      <webElementGuid>59f233e3-1404-4eff-9559-05072ea5c673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[3]/preceding::button[1]</value>
      <webElementGuid>2c3ec818-cb68-452b-9fc4-cd7f8fd89546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::button[2]</value>
      <webElementGuid>6de10372-3eb9-4ec4-aaab-609fad3089bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav/ul/li[4]/div/button</value>
      <webElementGuid>5759a086-a775-4433-bd60-8aae0940cf01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
      FAQ
    ' or . = '
      FAQ
    ')]</value>
      <webElementGuid>a3884300-48ac-411a-8417-23f0aecfe7c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
