<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mitra Kami 2</name>
   <tag></tag>
   <elementGuidId>5212c606-43d8-4ea2-a391-872cce84c7e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__layout&quot;]/div/div[2]/section[3]/div/div[2]/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>32506201-9437-44ca-b7e6-7bda8a9cd367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_nuxt/img/PBH.3705cd6.png</value>
      <webElementGuid>3cc2b310-5c22-4eab-8db0-a09a5ef8a1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-80 h-80 m-auto</value>
      <webElementGuid>9bebf346-7603-430e-8101-bf7f168392b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[2]/section[@class=&quot;our-partner&quot;]/div[@class=&quot;content-container
        lg:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        px-6
        md:px-0
        py-16
        md:flex md:justify-between&quot;]/div[@class=&quot;partner-logo mt-8 md:mt-0&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-3&quot;]/div[@class=&quot;bg-white
              rounded-lg
              shadow-lg
              p-4
              mr-4
              md:mr-0
              ml-0
              md:ml-4
              mb-4
              w-full
              md:w-32
              md:h-32&quot;]/div[@class=&quot;w-full h-full flex justify-center items-center relative&quot;]/div[1]/img[@class=&quot;w-80 h-80 m-auto&quot;]</value>
      <webElementGuid>ab05818a-8ef2-49f5-9bcf-40a871ae88dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/section[3]/div/div[2]/div/div[2]/div/div/img</value>
      <webElementGuid>3f8034ff-aef7-46a9-89b7-7d48834d5f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>6e3183ca-166f-4a40-8899-0dc6d0d42bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_nuxt/img/PBH.3705cd6.png']</value>
      <webElementGuid>6b67853b-929f-4fbe-904c-102fbad5d091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
