<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_kategori Pertanahan</name>
   <tag></tag>
   <elementGuidId>856a6e69-858b-4665-bc5b-9237cf70375a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='index-section']/div/section/div[2]/div[5]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>422e872a-ad6f-4cb8-b5af-31e46d924dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/public-perqara/icon/20220316_Marketing_Icon_Pertanahan.png</value>
      <webElementGuid>f2cbb265-5377-46fc-ade6-f03bfc4c5fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>e752e19e-04e5-4975-acbd-e15e19e2c10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index-section&quot;)/div[1]/section[@class=&quot;categories-filter mx-6 md:mx-0 my-16&quot;]/div[@class=&quot;grid grid-cols-2 md:grid-cols-5 xl:grid-cols-6 gap-5 my-10&quot;]/div[@class=&quot;categories-container
              shadow-lg
              h-48
              md:h-56
              w-full
              rounded-lg
              relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/div[@class=&quot;w-16
                    h-16
                    rounded-full
                    justify-center
                    items-center
                    flex
                    bg-white
                    m-auto&quot;]/img[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>8c568af8-9687-4946-aa93-7b48c0018a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='index-section']/div/section/div[2]/div[5]/div/div/div/img</value>
      <webElementGuid>901f8a03-dc5f-4104-8e80-79dc4ee925b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://storage.googleapis.com/public-perqara/icon/20220316_Marketing_Icon_Pertanahan.png')]</value>
      <webElementGuid>af216347-261d-47bc-922b-85fc9c874f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/img</value>
      <webElementGuid>3019a2dc-c80b-4214-8226-852a579a1b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/public-perqara/icon/20220316_Marketing_Icon_Pertanahan.png']</value>
      <webElementGuid>8e54b039-aba4-4ae1-8bd1-38d4e3574d73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
