<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Chat box</name>
   <tag></tag>
   <elementGuidId>2398254d-85e8-4e97-84a1-ac82fc0400e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qontak-webchat-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='qontak-webchat-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>be0f787d-c1b3-4272-952b-d6b360607611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://webchat.qontak.com?c=fPkthggPmqmq1U8OeMBGLA&amp;i=b3ba6f13-b622-47e0-88a4-fe173d7b80c2&amp;d=https://perqara.com&amp;w=1200&amp;h=707</value>
      <webElementGuid>b874410d-9513-4829-b38e-7b7978336cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qontak-webchat-widget</value>
      <webElementGuid>70ddd4cf-95a1-445d-84f0-b2f00e91471b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0aed915d-0fb1-44c6-b8c4-dcd5f6db69f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>066ed9c1-ef77-429d-afe6-8327509afaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webkitallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d26382f-3fcc-4fc1-86c7-3f3585cbc37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mozallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecb324f5-4e01-4d6b-a665-304bb4b33e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>380px</value>
      <webElementGuid>17539564-c049-4782-9199-b0f66f6af912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>590px</value>
      <webElementGuid>2bc4f4ad-5c2a-47f8-b5bc-01907b8d812b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat-widget&quot;)</value>
      <webElementGuid>0605c5aa-520e-4805-87d8-ddb493868961</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='qontak-webchat-widget']</value>
      <webElementGuid>6d5f2b52-5ebd-4fce-ac8c-7a6c79c9c123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>044bfed8-8081-4bbf-ac54-76081195d46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://webchat.qontak.com?c=fPkthggPmqmq1U8OeMBGLA&amp;i=b3ba6f13-b622-47e0-88a4-fe173d7b80c2&amp;d=https://perqara.com&amp;w=1200&amp;h=707' and @id = 'qontak-webchat-widget']</value>
      <webElementGuid>ceda941a-bae9-4fc0-9c0d-c291e1553b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
