<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Chat box sub title</name>
   <tag></tag>
   <elementGuidId>91ae8863-b207-4a91-a474-545321801c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.qchat-messenger__heading-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div/div/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4f6f1ae2-e466-49c8-a944-a844a098ad24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qchat-messenger__heading-title</value>
      <webElementGuid>28c69c7f-2690-4d26-958d-2b64942a7bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Halo! Ini adalah layanan Help Center Perqara </value>
      <webElementGuid>20d0d392-4e41-4ed8-bd4b-b6a435ec60ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat&quot;)/qontak-webchat[1]/div[1]/div[1]/div[1]/div[@class=&quot;qchat-messenger&quot;]/div[@class=&quot;q-d-flex&quot;]/div[@class=&quot;qchat-messenger__heading q-d-flex q-justify-content-between&quot;]/div[1]/p[@class=&quot;qchat-messenger__heading-title&quot;]</value>
      <webElementGuid>0c7f6ed7-7e63-496b-8540-e1dcb8f83a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Web Perqara/OBJR Home Unlogin Menu/OBJR Chat Box/iframe_Chat box</value>
      <webElementGuid>2e2e6aa4-8c15-4bed-a977-40d3a7ca3a99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div/div/div/div/div/p</value>
      <webElementGuid>c31f38e8-bc4b-464b-9358-96fa02151a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome!'])[1]/preceding::p[2]</value>
      <webElementGuid>72d671e9-c662-46ec-9f68-0de6f4e2f80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::p[2]</value>
      <webElementGuid>1b053975-0ffe-4e0b-bbc2-ea6f31effb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Halo! Ini adalah layanan Help Center Perqara']/parent::*</value>
      <webElementGuid>1bfbe276-cc01-4284-83a0-7847db6e7b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>867130d4-c1b4-47e8-ac09-d6995e52b510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' Halo! Ini adalah layanan Help Center Perqara ' or . = ' Halo! Ini adalah layanan Help Center Perqara ')]</value>
      <webElementGuid>0c74784a-e976-415d-9eea-ca886f43ca0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
