<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Chat box Email Address</name>
   <tag></tag>
   <elementGuidId>87ea8ecb-bb4d-49b7-b71a-5249f5250fec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e477da5-dee3-401e-94d1-dd848e902e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>dca6b228-d236-4c08-a90b-93c101b0e6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>e6957a3a-9600-4ab1-be22-03513a1d2941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-form-control q-mb-2 q-mt-1</value>
      <webElementGuid>60324f7d-3403-40bb-baf9-d69cdacad04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat&quot;)/qontak-webchat[1]/div[1]/div[1]/div[1]/div[@class=&quot;qchat-messenger&quot;]/div[@class=&quot;qchat-messenger-body&quot;]/div[2]/div[@class=&quot;qchat-messenger-form&quot;]/div[@class=&quot;qchat-form&quot;]/div[1]/input[@class=&quot;q-form-control q-mb-2 q-mt-1&quot;]</value>
      <webElementGuid>9fd6455b-8afa-482c-9de0-26dee01caf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Web Perqara/OBJR Home Unlogin Menu/OBJR Chat Box/iframe_Chat box</value>
      <webElementGuid>e7844c51-9c7e-4044-a030-35a9a95a033f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Email']</value>
      <webElementGuid>28d3c8d9-22d2-4989-8c26-d07ababe44bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div/div/div[2]/div[2]/div/div/div/input[2]</value>
      <webElementGuid>a5b46138-4b33-4e3c-959d-907f239fef52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>327c9843-9353-49b7-bb62-1aa4cee7116c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'Email']</value>
      <webElementGuid>323144e0-8190-4a3c-9a2f-342cb5ab3fd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
