<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_perqara Menu Bottom</name>
   <tag></tag>
   <elementGuidId>7912b133-44a7-47b5-b968-d5bc3a6c047b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[3]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div > img.w-32</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9608835a-be79-405e-99fe-954cd8b3c237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_nuxt/img/logo_perqara_white.e716f48.png</value>
      <webElementGuid>82365e25-59bd-4088-bdce-6af7a43f82b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-32</value>
      <webElementGuid>03b953ca-862a-4700-879b-2a7c8238a65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[3]/div[@class=&quot;bg-secondary md:absolute md:bottom-0 md:left-0 md:right-0&quot;]/div[@class=&quot;content-container
        lg:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        px-6
        md:px-0
        py-10&quot;]/div[@class=&quot;upper-section md:flex md:justify-between mb-10&quot;]/div[1]/img[@class=&quot;w-32&quot;]</value>
      <webElementGuid>ed89c2ff-07df-492c-82ad-70bff55dfaa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[3]/div/div/div/div/img</value>
      <webElementGuid>dd42615d-e077-4f21-8c40-63263b4bf9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/img</value>
      <webElementGuid>d8d4ff62-3f56-438c-8430-f81615ebc6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_nuxt/img/logo_perqara_white.e716f48.png']</value>
      <webElementGuid>ed242406-ad50-4d70-bff2-d05a678e66c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
