<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_menu bottom Jakarta Indonesia</name>
   <tag></tag>
   <elementGuidId>6d3355bc-f260-4d82-a4c8-41f11881b6b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[3]/div/div/div[3]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>feb59606-9472-4a80-8b53-2532af599695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm md:text-base</value>
      <webElementGuid>36da0ced-4812-423b-bd97-8e20f70358b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jakarta, Indonesia</value>
      <webElementGuid>64051274-88e8-4b7e-baec-170a10cde828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[3]/div[@class=&quot;bg-secondary md:absolute md:bottom-0 md:left-0 md:right-0&quot;]/div[@class=&quot;content-container
        lg:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        px-6
        md:px-0
        py-10&quot;]/div[@class=&quot;lower-section
          text-left
          md:text-center
          mt-10
          md:mt-0
          text-white
          font-avenir
          leading-loose&quot;]/p[@class=&quot;text-sm md:text-base&quot;]</value>
      <webElementGuid>a0c06fd8-eeee-451f-a358-5b72c0c308d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[3]/div/div/div[3]/p</value>
      <webElementGuid>ddb82631-924d-4f8c-8068-b385b8de55c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[5]/following::p[1]</value>
      <webElementGuid>cb272355-3cf2-4ab0-a343-a00e9374c86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[5]/following::p[1]</value>
      <webElementGuid>b0b3da2b-9926-4424-83a2-20bad89a29ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jakarta, Indonesia']/parent::*</value>
      <webElementGuid>1aa1430f-7043-4985-81a4-d236c360b252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/p</value>
      <webElementGuid>795f7c02-4bc9-4cb2-b27f-bc2f0ac7cb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Jakarta, Indonesia' or . = 'Jakarta, Indonesia')]</value>
      <webElementGuid>88511d2b-f2c6-4130-b171-6505d4c68c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
