<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>00_iframe_Chat box</name>
   <tag></tag>
   <elementGuidId>4726bda3-c640-4a5c-afc5-f1c6445578fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='qontak-webchat-widget']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#qontak-webchat-widget</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b8b39fce-ed96-423b-8d9c-e75b74142e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://webchat.qontak.com?c=fPkthggPmqmq1U8OeMBGLA&amp;i=b3ba6f13-b622-47e0-88a4-fe173d7b80c2&amp;d=https://perqara.com&amp;w=1200&amp;h=707</value>
      <webElementGuid>f0584fe6-c7b0-4901-be3a-2002456704e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qontak-webchat-widget</value>
      <webElementGuid>51c45eae-3d84-46b9-a424-717c116c797d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b1adf85-e478-4922-add3-d6b3ddb55db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>653bb8b2-c3bf-4ef4-bb14-8538ecfac2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webkitallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b45aaa3-d05c-4c30-b542-cd40cb577a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mozallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>89a132f6-5b64-4083-a6d3-0e2ea22fe90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>410px</value>
      <webElementGuid>0ca51cef-739e-448f-be11-3967aa638c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>160px</value>
      <webElementGuid>e27bbcd9-1174-4a4b-a0dc-fe6efa1a8059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat-widget&quot;)</value>
      <webElementGuid>3e097cee-909a-407b-b1f8-d5f19804e8cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='qontak-webchat-widget']</value>
      <webElementGuid>fb5b6d05-da5d-49a5-973f-b4ebb0bd4969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>aba8403c-95fa-4d4a-9db5-d9886fdf1d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://webchat.qontak.com?c=fPkthggPmqmq1U8OeMBGLA&amp;i=b3ba6f13-b622-47e0-88a4-fe173d7b80c2&amp;d=https://perqara.com&amp;w=1200&amp;h=707' and @id = 'qontak-webchat-widget']</value>
      <webElementGuid>1c9ee388-d39e-49d3-8145-ed41598e98f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
