<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>baloon_Chat kendala akses Perqara</name>
   <tag></tag>
   <elementGuidId>af108006-dd7d-428f-8b5e-f95fa91a6e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.qchat-box__box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e1b485f-1187-413e-bcf7-cc7c2b5e3a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qchat-box__box</value>
      <webElementGuid>7a68885f-9188-4aa7-bfda-acc718544211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kendala saat akses Perqara? Klik disini</value>
      <webElementGuid>ad738af5-174b-4099-8b95-f0ca9adc8eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat&quot;)/qontak-webchat[1]/div[1]/div[1]/div[@class=&quot;qchat-box__left&quot;]/div[@class=&quot;qchat-box__box&quot;]</value>
      <webElementGuid>c8e62b91-a400-4aed-a527-bbee3b7574e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Landing Page/OBJR Chat/00_iframe_Chat box</value>
      <webElementGuid>f1843ee1-f859-4467-8057-ab399216f017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div/div</value>
      <webElementGuid>8a516c29-5cf2-49a0-86c4-cb85886ad7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>eff5616d-eeda-45a8-8d26-9c976596ee8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kendala saat akses Perqara? Klik disini' or . = 'Kendala saat akses Perqara? Klik disini')]</value>
      <webElementGuid>7016370c-45de-4453-b169-a42b91bc861e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
