<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Chat circle</name>
   <tag></tag>
   <elementGuidId>2950e9c2-929a-4fd3-98fd-3bfe8c11bda7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.qchat-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd24e35b-a5f7-4392-a64e-f3ffe0e95597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qchat-button</value>
      <webElementGuid>a9d7bffc-9d5b-41ba-9c0c-3872c4b630bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat&quot;)/qontak-webchat[1]/div[1]/div[1]/div[@class=&quot;qchat-button&quot;]</value>
      <webElementGuid>09156b2b-1314-47d3-94a7-17bd886502a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Landing Page/OBJR Chat/00_iframe_Chat box</value>
      <webElementGuid>9ab2e6e0-5b61-4207-9aeb-8a20a0cec3c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div[2]</value>
      <webElementGuid>41bebf29-012c-441e-b605-815adea01bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>dbde01fc-e835-4a79-a3d4-444f76c8c9dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
