<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Chat kendala</name>
   <tag></tag>
   <elementGuidId>c897e1d8-98b0-4245-8a5d-ff4d071b58c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.qchat-box__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>75e8ef59-7ede-4b9c-8db5-762cb127c5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qchat-box__text</value>
      <webElementGuid>6064ff7a-e04e-4bd1-8ccb-afb0be66f2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kendala saat akses Perqara? Klik disini</value>
      <webElementGuid>9c27bad1-c3b5-41fc-9fc9-5b8ffd30fd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat&quot;)/qontak-webchat[1]/div[1]/div[1]/div[@class=&quot;qchat-box__left&quot;]/div[@class=&quot;qchat-box__box&quot;]/p[@class=&quot;qchat-box__text&quot;]</value>
      <webElementGuid>e69c8c6f-8702-45d1-b07d-3588cfeebe48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Landing Page/OBJR Chat/00_iframe_Chat box</value>
      <webElementGuid>d8211923-0403-4b4f-ae06-3305a22aac84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div/div/p</value>
      <webElementGuid>2e3fcb54-f56e-4204-adc5-529a77ebc9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kendala saat akses Perqara? Klik disini']/parent::*</value>
      <webElementGuid>35c928ac-2f4a-442b-8c63-e324af013214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>1c1b39fd-1083-457d-adb7-5af7e9a4a53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Kendala saat akses Perqara? Klik disini' or . = 'Kendala saat akses Perqara? Klik disini')]</value>
      <webElementGuid>60beb9b9-4b9c-45dd-88d5-b94092c01c9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
