<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mitra Kami 2</name>
   <tag></tag>
   <elementGuidId>5212c606-43d8-4ea2-a391-872cce84c7e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;partner-logo mt-8 md:mt-0&quot;]/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d2224c3b-bcca-49f0-9f7f-384b13d0dfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_nuxt/img/PBH.3705cd6.png</value>
      <webElementGuid>8f7766ec-404d-433a-9a0d-4c5a37256fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-80 h-80 m-auto</value>
      <webElementGuid>4b83c6fb-830b-4303-82a8-7586dd15f6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[2]/section[@class=&quot;our-partner&quot;]/div[@class=&quot;content-container
        lg:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        px-6
        md:px-0
        py-16
        md:flex md:justify-between&quot;]/div[@class=&quot;partner-logo mt-8 md:mt-0&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-3&quot;]/div[@class=&quot;bg-white
              rounded-lg
              shadow-lg
              p-4
              mr-4
              md:mr-0
              ml-0
              md:ml-4
              mb-4
              w-full
              md:w-32
              md:h-32&quot;]/div[@class=&quot;w-full h-full flex justify-center items-center relative&quot;]/div[1]/img[@class=&quot;w-80 h-80 m-auto&quot;]</value>
      <webElementGuid>ba862cf7-ac38-4765-9d07-392ff69902cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/section[3]/div/div[2]/div/div[2]/div/div/img</value>
      <webElementGuid>6dbcb0c2-bcf9-49dc-9678-e682fcd78f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>8cb223f7-d2da-4f4b-82e7-d37d1b3fb233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_nuxt/img/PBH.3705cd6.png']</value>
      <webElementGuid>f0dae191-cce1-433c-b09b-f4607958032e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
