<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_top advokat 1</name>
   <tag></tag>
   <elementGuidId>228ce79b-338e-4a4e-bbc3-119752ece21f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-5 my-10']/div[1]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dcfa3947-f15d-49c0-821b-bb9057a72c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666161742_YS%20Parsiholan.jpeg</value>
      <webElementGuid>7ec29480-82cf-477b-8751-5c806acade93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>75a7b242-dcb2-4396-9d8f-2b45498dfb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[2]/section[@class=&quot;lawyer-tesimonies&quot;]/div[@class=&quot;content-container
        lg:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        px-6
        md:px-0
        py-6
        md:py-16&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-5 my-10&quot;]/div[@class=&quot;categories-container
                  h-auto
                  md:h-auto
                  w-full
                  px-6
                  py-4
                  rounded-lg
                  relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/div[@class=&quot;w-72
                        h-32
                        justify-center
                        items-center
                        flex
                        bg-white
                        m-auto&quot;]/img[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>d3aeaa0f-0357-4ed4-8986-7e83fff325cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/section[2]/div/div/div/div/div/div/img</value>
      <webElementGuid>84f9ee69-7c48-42cf-bd3f-30473712e3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666161742_YS%20Parsiholan.jpeg')]</value>
      <webElementGuid>3531cbdd-60b5-4050-8008-8120b2b93cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/div/img</value>
      <webElementGuid>07b2b770-4912-480d-8172-d0b7c97eaa4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666161742_YS%20Parsiholan.jpeg']</value>
      <webElementGuid>511569c1-8635-40b7-86e3-a58d26da0f34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
