<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Keluar</name>
   <tag></tag>
   <elementGuidId>4e7164b4-91cf-4546-a6a0-81c9c8d376f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='flex']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c88dc98b-6f83-444c-9190-a626a931d8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nickolas</value>
      <webElementGuid>dd9ca9fd-642f-4adb-aea0-fb18d583a3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[1]/header[@class=&quot;font-avenir absolute w-full z-10&quot;]/div[@class=&quot;flex
        relative
        w-full
        md:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        py-8
        px-6
        md:px-0&quot;]/nav[@class=&quot;ml-5 font-avenir font-medium w-full&quot;]/ul[@class=&quot;flex md:pr-5&quot;]/li[@class=&quot;ml-auto&quot;]/ul[@class=&quot;flex&quot;]/li[@class=&quot;py-2 px-3 font-bold font-sf text-sm text-white&quot;]/button[1]</value>
      <webElementGuid>2a144154-81e5-4410-bb48-6775f0436877</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/header/div[2]/nav/ul/li[6]/ul/li[2]/button</value>
      <webElementGuid>847c2c64-f82d-4474-aa5e-9c784c490769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[2]/following::button[1]</value>
      <webElementGuid>4ed54282-7039-417f-8016-883b7b48c814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[3]/following::button[2]</value>
      <webElementGuid>39c6b57c-1b59-4ec4-9be0-776bab5a6429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[4]/preceding::button[1]</value>
      <webElementGuid>69a215b0-eead-4f1e-917f-8a453459c0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Advokat'])[4]/preceding::button[1]</value>
      <webElementGuid>97301351-8aef-4fdb-b836-c2b0c7763f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav/ul/li[6]/ul/li[2]/button</value>
      <webElementGuid>ce2dd5fa-488b-40b0-9285-3e6f9d9fc4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Nickolas' or . = 'Nickolas')]</value>
      <webElementGuid>1efcec4a-b802-4b1f-8f30-4b1f55186d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
