<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cari</name>
   <tag></tag>
   <elementGuidId>25d9f28c-1a9f-4016-8bf7-170b719b49d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a/button[contains(text(), 'Cari')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4dad90d8-f01f-462f-bbce-872cdb32abcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
              bg-primary
              leading-loose
              text-white
              py-1
              w-32
              rounded-lg
              mt-5
              md:mt-0
            </value>
      <webElementGuid>09854c2a-d257-4f68-b172-fa100434aa56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Cari
          </value>
      <webElementGuid>61adbc9d-4cba-4f15-82e2-7d27c54ba7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[2]/section[@class=&quot;header-banner relative w-full min-h-screen font-avenir&quot;]/div[@class=&quot;absolute h-screen w-full&quot;]/div[@class=&quot;relative
          md:px-0
          content-container
          lg:max-w-screen-lg
          xl:max-w-screen-xl
          mx-auto
          px-6
          py-8
          h-screen
          flex
          items-center&quot;]/div[@class=&quot;leading-loose&quot;]/div[@class=&quot;mt-6&quot;]/div[1]/div[@class=&quot;font-avenir hidden md:block&quot;]/div[@class=&quot;bg-white rounded-md px-8 py-5 md:p-0&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-4&quot;]/div[@class=&quot;text-left md:text-right my-auto px-8 pl-0&quot;]/a[1]/button[@class=&quot;bg-primary
              leading-loose
              text-white
              py-1
              w-32
              rounded-lg
              mt-5
              md:mt-0&quot;]</value>
      <webElementGuid>36eae918-9e44-4d08-936e-d53cfd1745dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/section/div/div/div/div[2]/div/div/div[2]/div/div[4]/a/button</value>
      <webElementGuid>9934054f-b7ce-481d-9551-2778c2f097ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gratis'])[1]/following::button[1]</value>
      <webElementGuid>c0ad32a8-5742-46b7-87a2-81c628872128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih berdasarkan kategori'])[1]/preceding::button[1]</value>
      <webElementGuid>0f6aa50c-6612-4a04-856a-9d291ecc06ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[1]/preceding::button[1]</value>
      <webElementGuid>60d20c54-a477-4fb9-8499-207aa5d97f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari']/parent::*</value>
      <webElementGuid>3ff28b92-b1f3-49cf-99d2-891390ca049c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/button</value>
      <webElementGuid>3a106d2a-cb18-4f1b-b2ce-f62d91e83a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
            Cari
          ' or . = '
            Cari
          ')]</value>
      <webElementGuid>20c5540e-03a5-41ee-b63e-634745add860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
