<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_label Perpajakan</name>
   <tag></tag>
   <elementGuidId>55d2f6f2-c61e-4df3-9bdd-02c2af4b0e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='index-section']/div/section/div[2]/div[6]/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a1343b1f-a92a-4f65-8b56-eee4beaa7883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-avenir text-sm md:text-base text-center mt-4</value>
      <webElementGuid>e2f4f857-aadd-44b1-baf9-d1349eb06396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Perpajakan
                </value>
      <webElementGuid>3c5af241-ab69-4537-b60b-7a932c57b60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index-section&quot;)/div[1]/section[@class=&quot;categories-filter mx-6 md:mx-0 my-16&quot;]/div[@class=&quot;grid grid-cols-2 md:grid-cols-5 xl:grid-cols-6 gap-5 my-10&quot;]/div[@class=&quot;categories-container
              shadow-lg
              h-48
              md:h-56
              w-full
              rounded-lg
              relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/p[@class=&quot;font-avenir text-sm md:text-base text-center mt-4&quot;]</value>
      <webElementGuid>054c9ca5-d732-4991-9cd5-358a3750c086</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='index-section']/div/section/div[2]/div[6]/div/div/p</value>
      <webElementGuid>79f8e3df-517b-4f89-83a7-bfe4a168c03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[5]/following::p[1]</value>
      <webElementGuid>4145cd68-c9d0-4fbd-8501-f10e554351d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[4]/following::p[2]</value>
      <webElementGuid>84622dae-e637-414f-9b08-1c040a843fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[6]/preceding::p[1]</value>
      <webElementGuid>a49bb344-5dc4-4909-99af-1b64b713b1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat lebih banyak'])[1]/preceding::p[1]</value>
      <webElementGuid>6ff87191-d16e-4fd2-a531-bef14aa71189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perpajakan']/parent::*</value>
      <webElementGuid>3ec59cff-dc5c-43fa-9cb2-8b035c3301e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/p</value>
      <webElementGuid>0cbb8ded-f9e9-4e18-aa7c-684aa577c16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                  Perpajakan
                ' or . = '
                  Perpajakan
                ')]</value>
      <webElementGuid>3df5a1e1-62a6-4722-96d9-7265709d662a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
