<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_label Pidana</name>
   <tag></tag>
   <elementGuidId>c9b59747-e7dd-46b7-a5c0-00a9f387b1cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='index-section']/div/section/div[2]/div[1]/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0e1773bf-5b34-41a7-b291-36b0941e9c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-avenir text-sm md:text-base text-center mt-4</value>
      <webElementGuid>ea310787-4718-4980-b9a6-88168ac4548c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Pidana
                </value>
      <webElementGuid>a9757c05-4dbb-400f-b3b2-b8ab979047e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index-section&quot;)/div[1]/section[@class=&quot;categories-filter mx-6 md:mx-0 my-16&quot;]/div[@class=&quot;grid grid-cols-2 md:grid-cols-5 xl:grid-cols-6 gap-5 my-10&quot;]/div[@class=&quot;categories-container
              shadow-lg
              h-48
              md:h-56
              w-full
              rounded-lg
              relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/p[@class=&quot;font-avenir text-sm md:text-base text-center mt-4&quot;]</value>
      <webElementGuid>08af813f-2721-47e9-9ed8-727b93217a40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='index-section']/div/section/div[2]/div/div/div/p</value>
      <webElementGuid>ca5537b8-77aa-4521-8c49-eca7a7c952f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih berdasarkan kategori'])[1]/following::p[2]</value>
      <webElementGuid>ea8c8862-a54f-4fd3-98b9-035785501aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::p[3]</value>
      <webElementGuid>17cf8beb-44b0-44dd-b883-eceab4bf1ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[1]/preceding::p[1]</value>
      <webElementGuid>20865dac-3445-4271-99b1-faced429a231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[2]/preceding::p[2]</value>
      <webElementGuid>8094ed74-c243-4aac-a902-c630597c07ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pidana']/parent::*</value>
      <webElementGuid>e24362d1-6afe-4097-9b5f-eb936734f110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p</value>
      <webElementGuid>7242a34f-e6ed-46c9-8e0a-d8541f0e7aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                  Pidana
                ' or . = '
                  Pidana
                ')]</value>
      <webElementGuid>d7c5e2c3-2045-45ec-9fed-120a163a263f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
