<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cari</name>
   <tag></tag>
   <elementGuidId>25d9f28c-1a9f-4016-8bf7-170b719b49d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/section/div/div/div/div[2]/div/div/div[2]/div/div[4]/a/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b3906d31-f5bb-4194-b97e-953984a5b70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
              bg-primary
              leading-loose
              text-white
              py-1
              w-32
              rounded-lg
              mt-5
              md:mt-0
            </value>
      <webElementGuid>5dce29d9-b3f0-405e-a0c7-3a6b04a5d609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Cari
          </value>
      <webElementGuid>1b7bfaac-6578-4bcf-a83c-e2805d6ddfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[2]/section[@class=&quot;header-banner relative w-full min-h-screen font-avenir&quot;]/div[@class=&quot;absolute h-screen w-full&quot;]/div[@class=&quot;relative
          md:px-0
          content-container
          lg:max-w-screen-lg
          xl:max-w-screen-xl
          mx-auto
          px-6
          py-8
          h-screen
          flex
          items-center&quot;]/div[@class=&quot;leading-loose&quot;]/div[@class=&quot;mt-6&quot;]/div[1]/div[@class=&quot;font-avenir hidden md:block&quot;]/div[@class=&quot;bg-white rounded-md px-8 py-5 md:p-0&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-4&quot;]/div[@class=&quot;text-left md:text-right my-auto px-8 pl-0&quot;]/a[1]/button[@class=&quot;bg-primary
              leading-loose
              text-white
              py-1
              w-32
              rounded-lg
              mt-5
              md:mt-0&quot;]</value>
      <webElementGuid>34b1f3b3-7657-41fe-9b89-6cc8a6b04d95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/section/div/div/div/div[2]/div/div/div[2]/div/div[4]/a/button</value>
      <webElementGuid>d431a5a2-5308-4bbf-9afd-0df3cfe871de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gratis'])[1]/following::button[1]</value>
      <webElementGuid>ac804b00-5a4c-4cad-9461-526e003166cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih berdasarkan kategori'])[1]/preceding::button[1]</value>
      <webElementGuid>8c1363b0-15b8-4fa0-b7f0-1900db4c1809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[1]/preceding::button[1]</value>
      <webElementGuid>e1d3815a-7b8c-44fa-817e-26553042397f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari']/parent::*</value>
      <webElementGuid>c2e8075a-62c3-4979-a2d8-cd99f405d1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/button</value>
      <webElementGuid>dce33288-d7c9-4642-ba5e-f5b52e705410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
            Cari
          ' or . = '
            Cari
          ')]</value>
      <webElementGuid>61a3ccea-2450-4ed4-bc3c-f18033a14eb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
