<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_perqara menu bottom</name>
   <tag></tag>
   <elementGuidId>7912b133-44a7-47b5-b968-d5bc3a6c047b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > img.w-32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='upper-section md:flex md:justify-between mb-10']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2a456cdf-9142-42a9-a4f5-ed251fd48b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_nuxt/img/logo_perqara_white.e716f48.png</value>
      <webElementGuid>8fc4be89-e30f-4b4a-a390-5b4d32d6e589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-32</value>
      <webElementGuid>a5d4d7af-54c0-40e6-b696-b4f469865d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[3]/div[@class=&quot;bg-secondary md:absolute md:bottom-0 md:left-0 md:right-0&quot;]/div[@class=&quot;content-container
        lg:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        px-6
        md:px-0
        py-10&quot;]/div[@class=&quot;upper-section md:flex md:justify-between mb-10&quot;]/div[1]/img[@class=&quot;w-32&quot;]</value>
      <webElementGuid>8bac2b3b-8693-4d9e-adfc-57f44f0e7e93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[3]/div/div/div/div/img</value>
      <webElementGuid>83b4284c-625d-4aa2-9725-83abac69448e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/img</value>
      <webElementGuid>fbedc5f0-8145-41ef-9f2f-9e55f1c715cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_nuxt/img/logo_perqara_white.e716f48.png']</value>
      <webElementGuid>b02d557d-6610-41d9-ae9c-1e97bcf09fa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
