<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Chat message x</name>
   <tag></tag>
   <elementGuidId>dea46c9a-eed7-4fcd-a6c9-2166742c0f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.emoji.border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='q-pointer q-ml-1']/*[local-name()='svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>34e14a66-f64a-4e1d-97d1-e25b2ffc23b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>emoji border</value>
      <webElementGuid>0cdbcc47-60e8-4fed-9d5c-289deddc20f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>😀</value>
      <webElementGuid>571f011e-1c0f-4323-ab5e-15ced4891dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Emojis&quot;)/div[@class=&quot;container-emoji&quot;]/div[@class=&quot;grid-emojis&quot;]/span[@class=&quot;emoji border&quot;]</value>
      <webElementGuid>a2be2351-f1c0-4ca6-a086-2df74d61bd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Web Perqara/OBJR Home Unlogin Menu/OBJR Chat Message/iframe_Chat message</value>
      <webElementGuid>51e81036-ad42-445e-9f8c-303c7e3161ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Emojis']/div/div/span</value>
      <webElementGuid>1dc6161b-6cfd-48c9-9141-4496370bcede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halo 2'])[1]/following::span[11]</value>
      <webElementGuid>8d01ea6f-9597-4022-a4d3-f52333fe1bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halo'])[1]/following::span[14]</value>
      <webElementGuid>8260f6b0-04f6-40b1-b8b6-01109c76beb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='😃'])[1]/preceding::span[1]</value>
      <webElementGuid>db1f7e8f-ea1a-4307-a637-d26f6467783a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='😄'])[1]/preceding::span[2]</value>
      <webElementGuid>21ed1c30-054f-4ca0-85c6-02a0c036717b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='😀']/parent::*</value>
      <webElementGuid>9a41a0a2-75fd-4d0d-8675-0d3a9b998590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span</value>
      <webElementGuid>1e0a1cac-786c-496c-9808-e8b48604785c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '😀' or . = '😀')]</value>
      <webElementGuid>05e4d1e7-a5b1-498e-9618-3b97e6216868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
