<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Kembali</name>
   <tag></tag>
   <elementGuidId>91f37335-bab3-4505-8195-25ab24c8c2b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class=&quot;my-auto flex nuxt-link-active&quot;]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a37d79bf-dae0-470a-ba59-387dcd03d5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
                      fas
                      fa-chevron-left
                      w-4
                      h-4
                      text-primary
                      font-bold
                      mr-1
                      text-xl
                    </value>
      <webElementGuid>f8f3c7c3-8315-423f-a14e-23f52581aece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a838c405-03e4-4324-9897-9841acda207f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[1]/div[@class=&quot;w-full h-100 font-avenir&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-3&quot;]/div[@class=&quot;md:h-screen md:w-full
          bg-white
          md:col-span-2 md:flex md:justify-center md:items-center&quot;]/div[@class=&quot;p-6 md:p-0 md:w-3/5&quot;]/div[1]/div[2]/div[@class=&quot;flex justify-between mt-10&quot;]/a[@class=&quot;my-auto flex nuxt-link-active&quot;]/i[@class=&quot;fas
                      fa-chevron-left
                      w-4
                      h-4
                      text-primary
                      font-bold
                      mr-1
                      text-xl&quot;]</value>
      <webElementGuid>323839cc-7aae-44c4-b19d-b7fbbaba81f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div[2]/div/div[2]/div/div/div[2]/div[4]/a/i</value>
      <webElementGuid>9c589c00-f53f-46f7-8a71-6d031a23a652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>9e41a6ac-20c5-451a-9a5b-6ef4f90bc275</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
