<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Chat circle</name>
   <tag></tag>
   <elementGuidId>c329cd3f-5e50-489e-b462-ec2378e63a45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.qchat-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='qchat-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9d49be1-67eb-4568-a05d-6c54993c06dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qchat-button</value>
      <webElementGuid>06e43bee-cfbd-43d2-837d-1ad7bad29b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat&quot;)/qontak-webchat[1]/div[1]/div[1]/div[@class=&quot;qchat-button&quot;]</value>
      <webElementGuid>6fc264d2-2762-43df-980d-2704558ab608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Web Perqara/OBJR Home Unlogin Menu/OBJR Chat/00_iframe_Chat box</value>
      <webElementGuid>c2e7253a-690e-4442-a3ba-9edc0ead48da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div[2]</value>
      <webElementGuid>8c1ee5b2-fdd2-4e27-8ca7-09a8b226d747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>337c5da5-8961-4459-b2c5-db4b43cdc1de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
