<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Chat box</name>
   <tag></tag>
   <elementGuidId>ea9c591a-b753-46b7-bf8d-084bc3fd6105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qontak-webchat-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='qontak-webchat-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d1d9866c-cf84-4e71-9176-720566727319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://webchat.qontak.com?c=fPkthggPmqmq1U8OeMBGLA&amp;i=b3ba6f13-b622-47e0-88a4-fe173d7b80c2&amp;d=https://perqara.com&amp;w=1200&amp;h=707</value>
      <webElementGuid>2c1d8597-22ed-42ed-ba0a-92a9c6e7403c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qontak-webchat-widget</value>
      <webElementGuid>038b48a8-88b2-4db9-9f4a-b6148463d606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>27b30282-9822-4454-a00e-7ac837419847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d656b12-93a2-48ac-8c91-71a8abde830e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webkitallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2055fd7d-0755-4c5c-aa1e-5f29476e7560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mozallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3367062f-b9af-417a-9ffe-dd038e3fb63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>410px</value>
      <webElementGuid>e069d6c5-3963-4c15-870f-085b43a9bc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>160px</value>
      <webElementGuid>5317aa0f-68ab-458e-bfd3-030e7802b5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat-widget&quot;)</value>
      <webElementGuid>0cbb3e58-030e-4320-8964-571b0717f251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='qontak-webchat-widget']</value>
      <webElementGuid>963e8f0d-e599-46c2-99e1-fc858268546c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a57fb5d3-6c7f-4d34-a9c2-6e6524e25c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://webchat.qontak.com?c=fPkthggPmqmq1U8OeMBGLA&amp;i=b3ba6f13-b622-47e0-88a4-fe173d7b80c2&amp;d=https://perqara.com&amp;w=1200&amp;h=707' and @id = 'qontak-webchat-widget']</value>
      <webElementGuid>e3ab83c6-a2f2-4dca-86cd-a9d2a20d4115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
