<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_top advokat 2</name>
   <tag></tag>
   <elementGuidId>f695250b-6634-4cb5-a4bb-b365c4555fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-5 my-10']/div[2]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>025f13cd-a229-480a-9ce5-b91d80da1c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666620053_Johanes%20Andri%20.jpeg</value>
      <webElementGuid>18634d6e-5d7a-4902-87e6-607ba2f6e5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>a2f26964-af39-4c6e-9f31-9070eff31785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[2]/section[@class=&quot;lawyer-tesimonies&quot;]/div[@class=&quot;content-container
        lg:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        px-6
        md:px-0
        py-6
        md:py-16&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-5 my-10&quot;]/div[@class=&quot;categories-container
                  h-auto
                  md:h-auto
                  w-full
                  px-6
                  py-4
                  rounded-lg
                  relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/div[@class=&quot;w-72
                        h-32
                        justify-center
                        items-center
                        flex
                        bg-white
                        m-auto&quot;]/img[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>48814e07-9fc2-4377-b053-51490d45f229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/section[2]/div/div/div[2]/div/div/div/img</value>
      <webElementGuid>0dd0c299-f091-429b-b9e2-b06270bdf49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666620053_Johanes%20Andri%20.jpeg')]</value>
      <webElementGuid>b384af8e-45c2-46a1-80d4-0fedaedeeee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/img</value>
      <webElementGuid>0f19681f-2c7f-470c-8622-29b7cf4ef342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666620053_Johanes%20Andri%20.jpeg']</value>
      <webElementGuid>1e898d64-16b4-4286-a0d1-62cde6857bf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
