<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>baloon_Chat kendala akses Perqara</name>
   <tag></tag>
   <elementGuidId>af108006-dd7d-428f-8b5e-f95fa91a6e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.qchat-box__box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='qchat-box__box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3996c62b-55df-4a57-8edd-19a7b8e67f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qchat-box__box</value>
      <webElementGuid>acd56dba-d0ba-4993-b54c-826fbc141f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kendala saat akses Perqara? Klik disini</value>
      <webElementGuid>6c4331ca-6fe4-46b3-98be-2679c7f01b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat&quot;)/qontak-webchat[1]/div[1]/div[1]/div[@class=&quot;qchat-box__left&quot;]/div[@class=&quot;qchat-box__box&quot;]</value>
      <webElementGuid>05574bc1-5a50-443d-96c4-42b1972dc7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Web Perqara/OBJR Home Unlogin Menu/OBJR Chat/00_iframe_Chat box</value>
      <webElementGuid>a5a537be-b20f-48d5-b544-f6188c03d1c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qontak-webchat']/qontak-webchat/div/div/div/div</value>
      <webElementGuid>4db353d0-c469-45c0-a70f-6766e86115bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>f247190c-6bdd-444a-9154-d0ce59c8bf48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kendala saat akses Perqara? Klik disini' or . = 'Kendala saat akses Perqara? Klik disini')]</value>
      <webElementGuid>66a625eb-8a66-4efc-b504-ca44863dbe0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
