<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Chat close</name>
   <tag></tag>
   <elementGuidId>8ef00816-b6f5-4b95-a823-9dec04053b8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.qchat-box__close-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='qchat-box__close d-flex qcentered-item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>c9af5129-6a28-4263-9641-b23995a57326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>47501ce8-e101-41cd-80f3-bab95318c2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 32 32</value>
      <webElementGuid>5922d765-5193-413b-9f2f-1abd23614304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>8ca0965c-64d3-4bef-8195-4ff4757f4a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>76155cf4-9743-46fb-bdb7-d77b92fefbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qchat-box__close-icon</value>
      <webElementGuid>8bfaeaa3-6d68-47d9-9ace-66ac843ce588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qontak-webchat&quot;)/qontak-webchat[1]/div[1]/div[1]/div[@class=&quot;qchat-box__left&quot;]/div[@class=&quot;qchat-box__box&quot;]/div[@class=&quot;qchat-box__close d-flex qcentered-item&quot;]/svg[@class=&quot;qchat-box__close-icon&quot;]</value>
      <webElementGuid>737b5692-0830-4d10-af22-c00399461164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJR Web Perqara/OBJR Home Unlogin Menu/OBJR Chat/00_iframe_Chat box</value>
      <webElementGuid>9c3e359b-aff9-408b-99b1-8dc1388fb651</webElementGuid>
   </webElementProperties>
</WebElementEntity>
