<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_kategori Perdata</name>
   <tag></tag>
   <elementGuidId>ca060e75-91df-4d0d-93b2-3381005f1df0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='index-section']/div/section/div[2]/div[2]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1342eab1-550f-4077-a8fe-cfa49a07f548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/public-perqara/icon/20220316_Marketing_Icon_Perdata.png</value>
      <webElementGuid>d1796003-3f53-435f-89e4-d3c018dc912b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>e7e6f3d9-5924-48e2-af44-1cc578b5405d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index-section&quot;)/div[1]/section[@class=&quot;categories-filter mx-6 md:mx-0 my-16&quot;]/div[@class=&quot;grid grid-cols-2 md:grid-cols-5 xl:grid-cols-6 gap-5 my-10&quot;]/div[@class=&quot;categories-container
              shadow-lg
              h-48
              md:h-56
              w-full
              rounded-lg
              relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/div[@class=&quot;w-16
                    h-16
                    rounded-full
                    justify-center
                    items-center
                    flex
                    bg-white
                    m-auto&quot;]/img[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>61ba984d-2d82-4fdb-b6e5-385ccdf7fa74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='index-section']/div/section/div[2]/div[2]/div/div/div/img</value>
      <webElementGuid>701558a9-c057-4874-8054-72bec56f5cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://storage.googleapis.com/public-perqara/icon/20220316_Marketing_Icon_Perdata.png')]</value>
      <webElementGuid>c23c53a9-632d-4e9e-9c95-6de61391c88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>14ef24a6-98a6-4682-b04e-ecfd33122135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/public-perqara/icon/20220316_Marketing_Icon_Perdata.png']</value>
      <webElementGuid>ec60d574-94b8-41f8-895f-baaf3c5670bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
