<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_label Perdata</name>
   <tag></tag>
   <elementGuidId>9cdeb5ed-cccd-4e1b-abbb-1249751abaa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='index-section']/div/section/div[2]/div[2]/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c66bd4b0-8625-4f5c-8449-66760f05ac07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-avenir text-sm md:text-base text-center mt-4</value>
      <webElementGuid>85b90726-deda-4b5a-ba5d-fbe67fc59d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Perdata
                </value>
      <webElementGuid>85960376-b99d-4b8a-860c-a7125e83d94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index-section&quot;)/div[1]/section[@class=&quot;categories-filter mx-6 md:mx-0 my-16&quot;]/div[@class=&quot;grid grid-cols-2 md:grid-cols-5 xl:grid-cols-6 gap-5 my-10&quot;]/div[@class=&quot;categories-container
              shadow-lg
              h-48
              md:h-56
              w-full
              rounded-lg
              relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/p[@class=&quot;font-avenir text-sm md:text-base text-center mt-4&quot;]</value>
      <webElementGuid>672ca5aa-5ff2-435b-9882-ddd6c218c7ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='index-section']/div/section/div[2]/div[2]/div/div/p</value>
      <webElementGuid>bff8452b-1252-4165-b3e2-3abf542dfb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[1]/following::p[1]</value>
      <webElementGuid>e3eb8d31-16d3-475b-a658-e174c1c18bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih berdasarkan kategori'])[1]/following::p[3]</value>
      <webElementGuid>9fed2806-0b17-4543-bacf-9d28c7aba443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[2]/preceding::p[1]</value>
      <webElementGuid>1b6c9eb9-8526-43cd-b55c-80b12954fd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[3]/preceding::p[2]</value>
      <webElementGuid>ac635aee-ad72-4a72-9afe-a6af9dbdf1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perdata']/parent::*</value>
      <webElementGuid>592d9e98-d27c-4937-9dad-0c7520364076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/p</value>
      <webElementGuid>1611685c-0b6d-4a8f-a309-c56c248b7996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                  Perdata
                ' or . = '
                  Perdata
                ')]</value>
      <webElementGuid>8955677a-dee9-4e02-99d8-bc6984372d0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
