<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_top advokat 1</name>
   <tag></tag>
   <elementGuidId>228ce79b-338e-4a4e-bbc3-119752ece21f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__layout&quot;]/div/div[2]/section[2]/div/div/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0701f9a8-5448-4aae-99d7-a0d60a93defc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666161742_YS%20Parsiholan.jpeg</value>
      <webElementGuid>65fbe90d-e3c6-4790-95fe-2e219e1092d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>dc649590-3bb5-468c-ad20-0b475c8db03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[2]/section[@class=&quot;lawyer-tesimonies&quot;]/div[@class=&quot;content-container
        lg:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        px-6
        md:px-0
        py-6
        md:py-16&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-5 my-10&quot;]/div[@class=&quot;categories-container
                  h-auto
                  md:h-auto
                  w-full
                  px-6
                  py-4
                  rounded-lg
                  relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/div[@class=&quot;w-72
                        h-32
                        justify-center
                        items-center
                        flex
                        bg-white
                        m-auto&quot;]/img[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>ed4e3c61-9b96-4d86-a610-507fe45eb29f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/section[2]/div/div/div/div/div/div/img</value>
      <webElementGuid>27558b0c-5071-407d-9372-4db748fbe9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666161742_YS%20Parsiholan.jpeg')]</value>
      <webElementGuid>49fe6cd1-bd86-45d1-988f-f90e51e24a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/div/img</value>
      <webElementGuid>d9bb57bf-3a60-4af9-89e5-5e05557c489d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666161742_YS%20Parsiholan.jpeg']</value>
      <webElementGuid>9708dff1-304f-4289-99a9-0c73aa11d9d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
