<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_top advokat 2</name>
   <tag></tag>
   <elementGuidId>f695250b-6634-4cb5-a4bb-b365c4555fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/section[2]/div/div/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>13162188-1d5a-4a84-be5c-3f2f6068c746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666620053_Johanes%20Andri%20.jpeg</value>
      <webElementGuid>90965823-8cfa-4ab2-a329-446bd75884a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>2b036257-5548-41ca-b622-51b5e414bad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[2]/section[@class=&quot;lawyer-tesimonies&quot;]/div[@class=&quot;content-container
        lg:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        px-6
        md:px-0
        py-6
        md:py-16&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-5 my-10&quot;]/div[@class=&quot;categories-container
                  h-auto
                  md:h-auto
                  w-full
                  px-6
                  py-4
                  rounded-lg
                  relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/div[@class=&quot;w-72
                        h-32
                        justify-center
                        items-center
                        flex
                        bg-white
                        m-auto&quot;]/img[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>3bcf858a-7a7d-4276-b51f-0dbe098ca33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/section[2]/div/div/div[2]/div/div/div/img</value>
      <webElementGuid>b3f45bda-b4ae-496f-bf17-0947007ba7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666620053_Johanes%20Andri%20.jpeg')]</value>
      <webElementGuid>cbea1b6d-8917-483b-ac81-3849884c73e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/img</value>
      <webElementGuid>36df34e4-fc49-41c7-b41f-3a8476ef421d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/perqara-belserion-production/belserion/public/profile/lawyer/picture/1666620053_Johanes%20Andri%20.jpeg']</value>
      <webElementGuid>005b1aae-8871-4284-a514-ca0528def074</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
