<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Pidana_1</name>
   <tag></tag>
   <elementGuidId>b5131cf0-3b11-4016-8e51-0dc3953bc9a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/section[2]/div/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a67279a2-6287-4345-8c2c-fe4eaed71dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-avenir text-sm sm:text-base text-center mt-8 bg-blue-400 text-white p-3 rounded-t-lg</value>
      <webElementGuid>7280b0ae-af70-435d-97e1-e6d027346b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Pidana
                </value>
      <webElementGuid>e31ac3b5-b0db-4977-880c-794eede48a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[2]/section[@class=&quot;lawyer-tesimonies&quot;]/div[@class=&quot;content-container
        lg:max-w-screen-lg
        xl:max-w-screen-xl
        mx-auto
        px-6
        md:px-0
        py-6
        md:py-16&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-5 my-10&quot;]/div[@class=&quot;categories-container
                  h-auto
                  md:h-auto
                  w-full
                  px-6
                  py-4
                  rounded-lg
                  relative&quot;]/div[@class=&quot;h-full flex justify-center items-center&quot;]/div[1]/p[@class=&quot;font-avenir text-sm sm:text-base text-center mt-8 bg-blue-400 text-white p-3 rounded-t-lg&quot;]</value>
      <webElementGuid>995c7d1b-1d77-47d6-87a2-5d410e3b1ef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/section[2]/div/div/div/div/div/p</value>
      <webElementGuid>b5b83a07-0136-4e27-990f-34ccd6495a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat lebih banyak'])[1]/following::p[4]</value>
      <webElementGuid>41e6f63e-86d3-4dd6-9f5c-de8942d5ade3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Kategori'])[6]/following::p[4]</value>
      <webElementGuid>6a64b5b1-4d40-47fd-a619-d8ce23c38cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mitra Kami'])[1]/preceding::p[6]</value>
      <webElementGuid>a1dca5a1-0b7d-4555-9695-b377a04fa618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[5]/preceding::p[6]</value>
      <webElementGuid>5888a7b1-d536-4346-9ae6-eed6e2023a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/p</value>
      <webElementGuid>f05cc1f4-9cd8-4a93-91b5-167d32363b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                Pidana
                ' or . = '
                Pidana
                ')]</value>
      <webElementGuid>aae6d0af-28fa-47ad-8f29-343c85b5ea00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
