<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Penting box main</name>
   <tag></tag>
   <elementGuidId>9aeffa03-abfc-4c28-b107-dc151689611e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bg-orange-100.border-l-4.border-orange-500.text-orange-700.p-4.mb-4.rounded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='alert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d8b367e9-1fbe-43d1-bfa9-51216386be03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>7f1685eb-ec3b-4689-b318-2858f140eb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4 mb-4 rounded</value>
      <webElementGuid>0a20719b-d18e-4768-9943-97fe3949bc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penting! Untuk pengalaman yang lebih baik gunakan browser Firefox atau Google Chrome.</value>
      <webElementGuid>dfeaa99a-34d1-4a2c-b5e2-ecad8fe67d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[1]/div[@class=&quot;z-50&quot;]/div[@class=&quot;login-container flex justify-center items-center&quot;]/div[@class=&quot;modal-content
        m-auto
        mx-3
        inline-block
        self-start
        align-bottom
        bg-secondary
        text-white
        rounded-2xl
        text-left
        overflow-hidden
        shadow-xl
        transform
        transition-all
        sm:align-middle sm:max-w-lg
        w-full&quot;]/div[@class=&quot;bg-white
          h-full
          rounded-2xl
          text-black
          py-4
          px-6
          md:py-6 md:px-10&quot;]/div[@class=&quot;bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4 mb-4 rounded&quot;]</value>
      <webElementGuid>d2fd5ce0-98cc-4a0c-ac7e-551747fdf66a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>1ef2fd6f-76be-4201-b1f9-72b26345d627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div</value>
      <webElementGuid>f7006d6a-8c07-4ff8-8c2e-b1f54408bc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Penting! Untuk pengalaman yang lebih baik gunakan browser Firefox atau Google Chrome.' or . = 'Penting! Untuk pengalaman yang lebih baik gunakan browser Firefox atau Google Chrome.')]</value>
      <webElementGuid>993e56f1-165d-49ee-8aba-5285ed024c95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
