<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Sandi</name>
   <tag></tag>
   <elementGuidId>80dbbf68-c9e4-492a-9095-9684db741dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.grid.mt-6 > label.mb-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@for='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>05851fc3-6237-4a03-ae3f-bf54d9457c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>649e8cc9-2123-4312-8732-82570eb3a27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-3</value>
      <webElementGuid>4d731fdd-fbd5-4239-9780-ba943b935f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sandi</value>
      <webElementGuid>af93ad31-490e-4c95-94a6-fb8fa476ff66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[1]/div[@class=&quot;z-50&quot;]/div[@class=&quot;login-container flex justify-center items-center&quot;]/div[@class=&quot;modal-content
        m-auto
        mx-3
        inline-block
        self-start
        align-bottom
        bg-secondary
        text-white
        rounded-2xl
        text-left
        overflow-hidden
        shadow-xl
        transform
        transition-all
        sm:align-middle sm:max-w-lg
        w-full&quot;]/div[@class=&quot;bg-white
          h-full
          rounded-2xl
          text-black
          py-4
          px-6
          md:py-6 md:px-10&quot;]/div[@class=&quot;form-container font-avenir&quot;]/div[@class=&quot;grid mt-6&quot;]/label[@class=&quot;mb-3&quot;]</value>
      <webElementGuid>32b63701-2d4f-48b3-b923-720ab2c3bc58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div[2]/div/div/div[2]/div[2]/div[2]/label</value>
      <webElementGuid>bfe819f0-67e5-4b6a-b8a8-2b9f16f38f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[1]</value>
      <webElementGuid>ba93029b-e695-4e72-ae73-fd5c676ce544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google Chrome'])[1]/following::label[2]</value>
      <webElementGuid>bf185fc7-752b-4ce3-b422-b44d227eb54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa sandi?'])[1]/preceding::label[1]</value>
      <webElementGuid>066a5b6e-19e8-404c-b4be-91d1da157ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::label[1]</value>
      <webElementGuid>aa82f9bc-fa1c-448b-9567-abbcc60887f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sandi']/parent::*</value>
      <webElementGuid>78fe601a-0784-4c14-bc81-3e8af98d7a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>0fdc1f1b-2772-43cf-8442-3b245b7a98fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Sandi' or . = 'Sandi')]</value>
      <webElementGuid>b7c464b2-a8af-489f-bcda-05a855bc08dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
