<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Email</name>
   <tag></tag>
   <elementGuidId>aa569441-e257-41b3-8762-a765376224fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0889f243-da8a-4d55-9651-837ce72e1ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68c47252-d22a-4c75-90d0-b358fb896774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan email anda</value>
      <webElementGuid>6c0006ec-6f63-4224-b40d-147138662502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input border-2 focus:border-secondary</value>
      <webElementGuid>ad6253b3-848c-45f3-bc6c-908f5bcc6f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;md:mb-56&quot;]/div[1]/div[@class=&quot;z-50&quot;]/div[@class=&quot;login-container flex justify-center items-center&quot;]/div[@class=&quot;modal-content
        m-auto
        mx-3
        inline-block
        self-start
        align-bottom
        bg-secondary
        text-white
        rounded-2xl
        text-left
        overflow-hidden
        shadow-xl
        transform
        transition-all
        sm:align-middle sm:max-w-lg
        w-full&quot;]/div[@class=&quot;bg-white
          h-full
          rounded-2xl
          text-black
          py-4
          px-6
          md:py-6 md:px-10&quot;]/div[@class=&quot;form-container font-avenir&quot;]/div[@class=&quot;grid&quot;]/input[@class=&quot;input border-2 focus:border-secondary&quot;]</value>
      <webElementGuid>18e9148e-2b4f-4fd4-958e-c0504af73092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>2a81ef41-a032-40e1-be99-c19d54037b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div[2]/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>640421c5-0811-486e-a105-fdb327df92c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>082e5857-1d85-4208-abb4-ca3e65baf8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan email anda']</value>
      <webElementGuid>dffe07e8-ceb0-42f8-859d-abe8faaf653f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
